<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="sticky-social" style="position:fixed;top:40%;left:-40px;padding:0px;margin:0px;">
        <ul class="social" style="list-style:none">
            <li class="fb" style="font-size: 25px;text-align: center;width: 45px;padding: 0;margin: 2px;background: #777777; transition: 0.5s all;margin-left: 0;border-radius: 50%;text-decoration: none !important;font-family: 'FontAwesome';height: 45px;line-height: 45px;display: block;" onMouseOver="this.style.background='#4267B2';this.style.transform='translateX(5px)';"
                onMouseOut="this.style.background='#777777';this.style.transform='translateX(0px)';"><a href="#" style="font-size: 25px;text-align: center;font-family: 'FontAwesome';line-height: 45px;"><i class="fa fa-facebook" aria-hidden="true" style="color:#fff;transition:all 0.8s ease-in-out;line-height: 45px;"></i></a></li>
            <li class="twitter" style="font-size: 25px;text-align: center;width: 45px;padding: 0;margin: 2px;background: #777777; transition: 0.5s all;margin-left: 0;border-radius: 50%;text-decoration: none !important;font-family: 'FontAwesome';height: 45px;line-height: 45px;display: block;" onMouseOver="this.style.background='#1DA1F2';this.style.transform='translateX(5px)';"
                onMouseOut="this.style.background='#777777';this.style.transform='translateX(0px)';"><a href="#" style="font-size: 25px;text-align: center;font-family: 'FontAwesome';line-height: 45px;"><i class="fa fa-twitter" aria-hidden="true" style="color:#fff;transition:all 0.8s ease-in-out;line-height: 45px;"></i></a></li>
            <li class="insta" style="font-size: 25px;text-align: center;width: 45px;padding: 0;margin: 2px;background: #777777; transition: 0.5s all;margin-left: 0;border-radius: 50%;text-decoration: none !important;font-family: 'FontAwesome';height: 45px;line-height: 45px;display: block;" onMouseOver="this.style.background='#DC4F42';this.style.transform='translateX(5px)';"
                onMouseOut="this.style.background='#777777';this.style.transform='translateX(0px)';"><a href="#" style="font-size: 25px;text-align: center;font-family: 'FontAwesome';line-height: 45px;"><i class="fa fa-instagram" aria-hidden="true" style="color:#fff;transition:all 0.8s ease-in-out;line-height: 45px;"></i></a></li>
            <li class="pin" style="font-size: 25px;text-align: center;width: 45px;padding: 0;margin: 2px;background: #777777; transition: 0.5s all;margin-left: 0;border-radius: 50%;text-decoration: none !important;font-family: 'FontAwesome';height: 45px;line-height: 45px;display: block;" onMouseOver="this.style.background='#CB2128';this.style.transform='translateX(5px)';"
                onMouseOut="this.style.background='#777777';this.style.transform='translateX(0px)';"><a href="#" style="font-size: 25px;text-align: center;font-family: 'FontAwesome';line-height: 45px;"><i class="fa fa-pinterest-p" aria-hidden="true" style="color:#fff;transition:all 0.8s ease-in-out;line-height: 45px;"></i></a></li>
            <li class="vim" style="font-size: 25px;text-align: center;width: 45px;padding: 0;margin: 2px;background: #777777; transition: 0.5s all;margin-left: 0;border-radius: 50%;text-decoration: none !important;font-family: 'FontAwesome';height: 45px;line-height: 45px;display: block;" onMouseOver="this.style.background='#59BFBE';this.style.transform='translateX(5px)';"
                onMouseOut="this.style.background='#777777';this.style.transform='translateX(0px)';"><a href="#" style="font-size: 25px;text-align: center;font-family: 'FontAwesome';line-height: 45px;"><i class="fa fa-vimeo" aria-hidden="true" style="color:#fff;transition:all 0.8s ease-in-out;line-height: 45px;"></i></a></li>
        </ul>
    </div>
