<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get(
            '/merchants',
            App\Livewire\Dashboard\MerchantIndex::class
        )->name('merchants.index');

        Route::get(
            '/merchants/create',
            App\Livewire\Dashboard\MerchantCreate::class
        )->name('merchants.create');

        Route::get(
            '/merchants/{merchant}',
            App\Livewire\Dashboard\MerchantEdit::class
        )->name('merchants.edit');

        Route::get(
            '/webhooks',
            App\Livewire\Dashboard\WebhookIndex::class
        )->name('webhooks.index');

        Route::get(
            '/webhooks/create',
            App\Livewire\Dashboard\WebhookCreate::class
        )->name('webhooks.create');

        Route::get(
            '/webhooks/{webhook}',
            App\Livewire\Dashboard\WebhookEdit::class
        )->name('webhooks.edit');

        Route::get(
            '/social-configurations',
            App\Livewire\Dashboard\SocialConfigurationIndex::class
        )->name('social-configurations.index');

        Route::get(
            '/social-configurations/create',
            App\Livewire\Dashboard\SocialConfigurationCreate::class
        )->name('social-configurations.create');

        Route::get(
            '/social-configurations/{socialConfiguration}',
            App\Livewire\Dashboard\SocialConfigurationEdit::class
        )->name('social-configurations.edit');

        Route::get(
            '/store-and-product-webhooks',
            App\Livewire\Dashboard\StoreAndProductWebhookIndex::class
        )->name('store-and-product-webhooks.index');

        Route::get(
            '/store-and-product-webhooks/create',
            App\Livewire\Dashboard\StoreAndProductWebhookCreate::class
        )->name('store-and-product-webhooks.create');

        Route::get(
            '/store-and-product-webhooks/{storeAndProductWebhook}',
            App\Livewire\Dashboard\StoreAndProductWebhookEdit::class
        )->name('store-and-product-webhooks.edit');

        Route::get(
            '/store-product-reviews-merchants',
            App\Livewire\Dashboard\StoreProductReviewsMerchantIndex::class
        )->name('store-product-reviews-merchants.index');

        Route::get(
            '/store-product-reviews-merchants/create',
            App\Livewire\Dashboard\StoreProductReviewsMerchantCreate::class
        )->name('store-product-reviews-merchants.create');

        Route::get(
            '/store-product-reviews-merchants/{storeProductReviewsMerchant}',
            App\Livewire\Dashboard\StoreProductReviewsMerchantEdit::class
        )->name('store-product-reviews-merchants.edit');

        Route::get(
            '/store-product-reviews-configurations',
            App\Livewire\Dashboard\StoreProductReviewsConfigurationIndex::class
        )->name('store-product-reviews-configurations.index');

        Route::get(
            '/store-product-reviews-configurations/create',
            App\Livewire\Dashboard\StoreProductReviewsConfigurationCreate::class
        )->name('store-product-reviews-configurations.create');

        Route::get(
            '/store-product-reviews-configurations/{storeProductReviewsConfiguration}',
            App\Livewire\Dashboard\StoreProductReviewsConfigurationEdit::class
        )->name('store-product-reviews-configurations.edit');

        Route::get(
            '/voice-merchants',
            App\Livewire\Dashboard\VoiceMerchantIndex::class
        )->name('voice-merchants.index');

        Route::get(
            '/voice-merchants/create',
            App\Livewire\Dashboard\VoiceMerchantCreate::class
        )->name('voice-merchants.create');

        Route::get(
            '/voice-merchants/{voiceMerchant}',
            App\Livewire\Dashboard\VoiceMerchantEdit::class
        )->name('voice-merchants.edit');

        Route::get(
            '/voice-webhooks',
            App\Livewire\Dashboard\VoiceWebhookIndex::class
        )->name('voice-webhooks.index');

        Route::get(
            '/voice-plan-configurations',
            App\Livewire\Dashboard\VoicePlanConfigurationIndex::class
        )->name('voice-plan-configurations.index');

        Route::get(
            '/voice-plan-configurations/create',
            App\Livewire\Dashboard\VoicePlanConfigurationCreate::class
        )->name('voice-plan-configurations.create');

        Route::get(
            '/voice-plan-configurations/{voicePlanConfiguration}',
            App\Livewire\Dashboard\VoicePlanConfigurationEdit::class
        )->name('voice-plan-configurations.edit');

        Route::get(
            '/voice-ai-configuration',
            App\Livewire\Dashboard\VoiceAiConfigurationEdit::class
        )->name('voice-ai-configuration.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
