<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get(
            '/merchants',
            App\Livewire\Dashboard\MerchantIndex::class
        )->name('merchants.index');

        Route::get(
            '/merchants/create',
            App\Livewire\Dashboard\MerchantCreate::class
        )->name('merchants.create');

        Route::get(
            '/merchants/{merchant}',
            App\Livewire\Dashboard\MerchantEdit::class
        )->name('merchants.edit');

        Route::get(
            '/webhooks',
            App\Livewire\Dashboard\WebhookIndex::class
        )->name('webhooks.index');

        Route::get(
            '/webhooks/create',
            App\Livewire\Dashboard\WebhookCreate::class
        )->name('webhooks.create');

        Route::get(
            '/webhooks/{webhook}',
            App\Livewire\Dashboard\WebhookEdit::class
        )->name('webhooks.edit');

        Route::get(
            '/social-configurations',
            App\Livewire\Dashboard\SocialConfigurationIndex::class
        )->name('social-configurations.index');

        Route::get(
            '/social-configurations/create',
            App\Livewire\Dashboard\SocialConfigurationCreate::class
        )->name('social-configurations.create');

        Route::get(
            '/social-configurations/{socialConfiguration}',
            App\Livewire\Dashboard\SocialConfigurationEdit::class
        )->name('social-configurations.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
